---
- name: Localizar e transferir arquivos
  hosts: "{{ target_host }}"
  strategy: free
  ignore_unreachable: yes
  remote_user: root
  vars:
    ansible_ssh_pass: "{{ senha }}"

  tasks:
    - name: Garantir que o diretório de destino exista no host local
      delegate_to: localhost
      file:
        path: "{{ diretorio_destino }}"
        state: directory
        mode: '0755'

    - name: Obter arquivos recentes
      shell: "find /home/bkpComunix -iname '*.tar.gz' -ctime -1"
      register: arquivos_recentes
      ignore_errors: yes

    - name: Exibir arquivos recentes
      debug:
        var: arquivos_recentes

    - name: Copiar arquivos via rsync sem verificar fingerprint
      command: >
        sshpass -p "{{ senha }}" rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no" {{ item }}
        root@192.168.2.167:"{{ diretorio_destino }}"
      with_items: "{{ arquivos_recentes.stdout_lines }}"
      when: arquivos_recentes.stdout_lines is defined
