---
- name: Transferir arquivos
  hosts: "{{ target_host }}"
  vars:
    backup_base_dir: "{{ destino_backup }}"
  tasks:
    - name: Obter todos os arquivos recentes
      shell: "find /home/bkpComunix -iname '*.tar.gz' -ctime -1"
      register: arquivos_recentes

    - name: Verificar se foram encontrados arquivos recentes
      fail:
        msg: "Nenhum arquivo recente encontrado em /home/bkpComunix"
      when: arquivos_recentes.stdout_lines is not defined or arquivos_recentes.stdout_lines | length == 0

    - name: Verificar os arquivos encontrados
      debug:
        msg: "Arquivos recentes encontrados: {{ arquivos_recentes.stdout_lines }}"

    - name: Criar diretório local para os arquivos com base no grupo
      file:
        path: "{{ backup_base_dir }}/{{ group_names[0] }}/{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost

    - name: Copiar os arquivos recentes do remoto para o diretório correspondente
      fetch:
        src: "{{ item }}"
        dest: "{{ backup_base_dir }}/{{ group_names[0] }}/{{ inventory_hostname }}/"
        flat: yes
      loop: "{{ arquivos_recentes.stdout_lines }}"

